name: assets
description: Loading assets using the Dart asset bundle system.
version: 0.1.0
repository: https://github.com/dart-lang/core/tree/main/pkgs/assets
issue_tracker: https://github.com/dart-lang/core/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Aassets

environment:
  sdk: ^3.7.0

dependencies:
  http: ^1.1.0
  logging: ^1.3.0
  meta: ^1.16.0
  native_assets_cli: ^0.11.0
  record_use: ^0.3.0

dev_dependencies:
  dart_flutter_team_lints: ^3.4.0
  lints: ^5.1.1
  test: ^1.24.0
