# Configuration for .github/workflows/pull_request_label.yml.

'type-infra':
  - changed-files:
    - any-glob-to-any-file: '.github/**'

'package:args':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/args/**'

'package:async':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/async/**'

'package:characters':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/characters/**'

'package:collection':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/collection/**'

'package:convert':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/convert/**'

'package:crypto':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/crypto/**'

'package:fixnum':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/fixnum/**'

'package:logging':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/logging/**'

'package:os_detect':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/os_detect/**'

'package:path':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/path/**'

'package:platform':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/platform/**'

'package:typed_data':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/typed_data/**'
