name: os_detect
version: 2.0.3
description: Platform independent OS detection.
repository: https://github.com/dart-lang/core/tree/main/pkgs/os_detect
issue_tracker: https://github.com/dart-lang/core/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Aos_detect

environment:
  sdk: ^3.5.0

dependencies:
  meta: ^1.9.0
  web: ^1.0.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.24.0
