name: path
version: 1.9.2-wip
description: A string-based path manipulation library.  
repository: https://github.com/dart-lang/core/tree/main/pkgs/path
issue_tracker: https://github.com/dart-lang/core/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Apath

topics:
 - file-system

environment:
  sdk: ^3.4.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.6
  web: ^1.0.0
