name: Groundskeeper
permissions:
  contents: read

on:
  schedule:
    - cron: '0 0 * * *' # Daily at 00:00 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  tidy:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        package:
          - args
          - async
          - characters
          - collection
          - convert
          - crypto
          - fixnum
          - lints
          - logging
          - os_detect
          - path
          - platform
          - typed_data
    uses: dart-lang/ecosystem/.github/workflows/groundskeeper.yml@fc3dd9a17a8e18b3b4aa5abac8a0f4a679fe2d57
    with:
      directory: pkgs/${{ matrix.package }}
      branch: auto-tidy-${{ matrix.package }}
      title: 'Tidy: package:${{ matrix.package }}'
    secrets: inherit # zizmor: ignore[secrets-inherit]
